version: '3.3'
services:
  amerigo:
    image: sc-registry.fredhutch.org/amerigo:latest
    networks:
      - proxytemp
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.amerigo.rule=Host(`amerigo.fredhutch.org`)"
        - "traefik.http.routers.amerigo-secured.rule=Host(`amerigo.fredhutch.org`)"
        - "traefik.http.routers.amerigo.entrypoints=web,web-secured"
        - "traefik.http.services.amerigo.loadbalancer.server.port=3838" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.amerigo.tls=true"

networks:
  proxytemp:
    external: true